/************************************************************************************************************
* PhillyInvaders Game																						*
*																											*
* A simple space invaders like game which makes use of the AvaacGL graphics renderer						*
*																											*
* Author: Phillip Haddad																					*
*																											*
* ***********************************************************************************************************/

#ifndef __RESOURCES_ENUM_H__
#define __RESOURCES_ENUM_H__

// So when I first started doing this my plan was to make this enum header an autogenerated file with an external
// tool because it would be easy and efficient to do. That being said for the purposes of this project I've decided
// to manually hand craft this file. If I'm asked to later I can easily create the tool to do this part

typedef enum rcIDs_e
{
	IMAGE_SPACE_BACKGROUND	= 0,
	IMAGE_PLAYER_SHIP,
	IMAGE_PLAYER_PROJECTILE,
	IMAGE_ENEMY_SHIP,
	IMAGE_ENEMY_PROJECTILE,
	IMAGE_SHIP_HEALTH_BAR,

} rcID;

#endif
